services:
  api:
    image: ${API_IMAGE_NAME}:${API_IMAGE_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      args:
        - GO_IMAGE_VERSION=${GO_IMAGE_VERSION}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
