name: Docker Image Build

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'The version of the Docker image'
        required: true
      scope:
        description: 'Beta/Release ?'
        type: choice
        options:
          - 'BETA'
          - 'RELEASE'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # We have to lower case the repository name in order to push it to the GitHub Container Registry
      - uses: actions/checkout@v4
      - name: Retrieve the repository name
        working-directory: ./docker/api
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Building the Docker image
        run: |
          if [ "${{ inputs.scope }}" = "BETA" ]; then
            docker build . -f ./docker/api/Dockerfile --tag ghcr.io/${REPO}:${{ inputs.image_version }} --tag ghcr.io/${REPO}:latest-beta
          else
            docker build . -f ./docker/api/Dockerfile --tag ghcr.io/${REPO}:${{ inputs.image_version }} --tag ghcr.io/${REPO}:latest
          fi

      - name: Pushing the Docker image
        run: |
          docker login ghcr.io -u ${REPO} -p ${{ secrets.GITHUB_TOKEN }}
          if [ "${{ inputs.scope }}" = "BETA" ]; then
            docker push ghcr.io/${REPO}:latest-beta
            docker push ghcr.io/${REPO}:${{ inputs.image_version }}
          else
            docker push ghcr.io/${REPO}:latest
            docker push ghcr.io/${REPO}:${{ inputs.image_version }}
          fi

      - name: Pushing tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          tag_prefix: ""
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ inputs.image_version }}